import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Code Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images.jpg" />
      </Head>

      <main className={styles.main}>
        <h2>Code Blog</h2>

        <img
          className={styles.imgwrap}
          src="/images.jpg"
          width={50}
          height={50}
        />

        <p className={styles.description}>Created for Coder!</p>

        <div className={styles.main}>
          <h1>Populer Blog</h1>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h3>Learn JavaScript &rarr;</h3>
              <p>
                Find in-depth information about Javascript features and API.
              </p>
            </div>
            <div className={styles.card}>
              <h3>Learn React Js &rarr;</h3>
              <p>Learn about React Js in an interactive course with quizzes!</p>
            </div>

            <div className={styles.card}>
              <h3>learn Next Js &rarr;</h3>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </div>

            <div className={styles.card}>
              <h3>Learn Web Developmnt &rarr;</h3>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <h4>creted for coders</h4>
      </footer>
    </div>
  );
}
